# config_verification_v2.yaml
# Verification run with NEW exploration-dependent questions (V2)
# Purpose: Verify Observer scores <40% (can't answer without exploration)

models:
  observer:
    model: "claude-sonnet-4-5-20250929"
  a_c_e:
    model: "claude-sonnet-4-5-20250929"
  judge:
    model: "gpt-4-0125-preview"

budgets:
  actions_per_episode: 10
  tokens_per_call: 2000

agents:
  - observer  # Should score <40% on V2 questions
  - ace       # Should score >60% on V2 questions

environments:
  hot_pot:
    num_episodes: 5
    seeds: [1000, 1001, 1002, 1003, 1004]

# Total: 10 episodes (2 agents × 1 environment × 5 seeds)
# Expected cost: ~$5
# Expected time: ~10 minutes
# SUCCESS CRITERIA:
#   - Observer accuracy <40% (proves questions require exploration)
#   - ACE accuracy >60% (proves exploration helps)
#   - ACE outperforms Observer by >20 percentage points
