# ACE Pilot: 10 episodes (5 HotPot + 5 SwitchLight)
# Fair comparison with existing pilot data

models:
  observer:
    model: "claude-sonnet-4-5-20250929"
  actor:
    model: "claude-sonnet-4-5-20250929"
  a_c_e:
    model: "claude-sonnet-4-5-20250929"
  text_reader:
    model: "claude-sonnet-4-5-20250929"
  judge:
    model: "gpt-4-0125-preview"

budgets:
  actions_per_episode: 10
  tokens_per_call: 2000

agents:
  - a_c_e

environments:
  hot_pot:
    num_episodes: 5
    seeds: [42, 43, 44, 45, 46]  # Same seeds as other agents
  switch_light:
    num_episodes: 5
    seeds: [100, 101, 102, 103, 104]  # Same seeds as other agents
