# Pilot Configuration for H1-H5 Agent Comparison Hypotheses
# 30 episodes total: 3 agents × 2 environments × 5 episodes

experiment:
  name: "h1h5_pilot"
  description: "Pilot test of H1-H5 agent comparison hypotheses"
  preregistration_file: "preregistration.yaml"

models:
  observer:
    model: "claude-sonnet-4-5-20250929"
  actor:
    model: "claude-sonnet-4-5-20250929"
  model_based:
    model: "claude-sonnet-4-5-20250929"
  text_reader:
    model: "claude-sonnet-4-5-20250929"

budgets:
  actions_per_episode: 10
  tokens_per_call: 2000

environments:
  hot_pot:
    num_episodes: 5
    seeds: [1001, 1002, 1003, 1004, 1005]

  switch_light:
    num_episodes: 5
    seeds: [2001, 2002, 2003, 2004, 2005]

preregistration:
  file: "preregistration.yaml"
  verify_hash: false
  enforce_hypotheses: true
